name: iK my first github action pipeline to build & push my docker-compse app to Heroku

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: iK collecting our git repo using checkout
    - uses: actions/checkout@v2

    - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
      id: heroku
      uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
      with:
        email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
        api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
        docker_compose_file: '.' # set the path to the folder where the docker-compose file is located
        heroku_apps: '[{"imagename":"nextapp","appname":"v8tests","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
